name: "\U0001F680 Experiment"
description: Log experiments for research
labels: [ "experiment" ]
body:
  - type: textarea
    id: experiment
    validations:
      required: true
    attributes:
      label: Experiment
      description: |
        A brief description of the experiment

  - type: textarea
    id: todo
    validations:
      required: true
    attributes:
      label: To-Dos
      description: |
        List out to-dos to complete the experiment.
      value: |
        - [ ] 
        - [ ] 
        - [ ] 

  - type: textarea
    id: note
    validations:
      required: false
    attributes:
      label: note
      description: |
        Any notes about the experiment.